name: custom Version Bump

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Select version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major



jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Universal Version Bump
        uses: taj54/universal-version-bump@v0.13.1
        with:
          release_type: ${{ inputs.release_type }}
          git_tag: false
          target_platform: 'custom'
          bump_targets: |
            [
              { "path": "package.json", "variable": "version" },
              { "path": "node-demo/package.json", "variable": "version" },
               {"path":"php-config-demo/config.php", "variable": "version"}
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
