name: Version Bump

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Select version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      target_path:
        description: 'Directory to bump version in'
        required: true
        default: 'node-demo'
        type: choice
        options:
          - .
          - node-demo
          - python-toml-demo
          - python-setup-demo
          - php-composer-demo
          - php-version-php-demo
          - php-config-demo
          - docker-demo
          - rust-demo



jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Universal Version Bump
        uses: taj54/universal-version-bump@v0.8.11
        with:
          release_type: ${{ inputs.release_type }}
          git_tag: false
          target_path: ${{ inputs.target_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
